import type { Metadata } from 'next'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import { ThemeProvider } from '@mui/material/styles'
import CssBaseline from '@mui/material/CssBaseline'
import { theme } from '@/theme'
import { Roboto } from 'next/font/google'
import { Navigation } from '@/components'
import { SWRProvider } from '@/app/providers'
import styles from './layout.module.scss'
import './globals.css'

const roboto = Roboto({
	weight: ['300', '400', '500', '700'],
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-roboto',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className={roboto.variable}>
			<body>
				<SWRProvider>
					<AppRouterCacheProvider>
						<ThemeProvider theme={theme}>
							<CssBaseline />
							<div className={styles.container}>
								<Navigation />
								<div className={styles.content}>{children}</div>
							</div>
						</ThemeProvider>
					</AppRouterCacheProvider>
				</SWRProvider>
			</body>
		</html>
	)
}
